// Unity Build Uber File generated by CMake
// This file is auto generated, do not manually edit it.

#include <StdAfx.h>
#include <C:/Users/user/Documents/CRYENGINE Projects/War Machine/Code/Components/Player.cpp>

